//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PTTGC_CSREntities : DbContext
{
    public PTTGC_CSREntities()
        : base("name=PTTGC_CSREntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<MT_CCTR_Structure> MT_CCTR_Structure { get; set; }
    public virtual DbSet<MT_CostCenter> MT_CostCenter { get; set; }
    public virtual DbSet<MT_GLAccount> MT_GLAccount { get; set; }
    public virtual DbSet<MT_InternalOrder> MT_InternalOrder { get; set; }
    public virtual DbSet<T_Project> T_Project { get; set; }
    public virtual DbSet<T_Project_Approve> T_Project_Approve { get; set; }
    public virtual DbSet<T_Project_File> T_Project_File { get; set; }
    public virtual DbSet<TB_Budget> TB_Budget { get; set; }
    public virtual DbSet<TB_Budget_Sub> TB_Budget_Sub { get; set; }
    public virtual DbSet<TB_Change_Owner> TB_Change_Owner { get; set; }
    public virtual DbSet<TB_CostCenter> TB_CostCenter { get; set; }
    public virtual DbSet<TB_DateSync> TB_DateSync { get; set; }
    public virtual DbSet<TB_GLAccount> TB_GLAccount { get; set; }
    public virtual DbSet<TB_InternalOrder> TB_InternalOrder { get; set; }
    public virtual DbSet<TB_Map_Budget> TB_Map_Budget { get; set; }
    public virtual DbSet<TB_Map_Budget_Sub> TB_Map_Budget_Sub { get; set; }
    public virtual DbSet<TB_User> TB_User { get; set; }
    public virtual DbSet<TB_User_Permission> TB_User_Permission { get; set; }
    public virtual DbSet<TM_Log> TM_Log { get; set; }
    public virtual DbSet<TM_LogMail> TM_LogMail { get; set; }
    public virtual DbSet<TM_MasterData> TM_MasterData { get; set; }
    public virtual DbSet<TM_MasterData_Sub> TM_MasterData_Sub { get; set; }
    public virtual DbSet<TM_Menu> TM_Menu { get; set; }
    public virtual DbSet<TM_Organization> TM_Organization { get; set; }
    public virtual DbSet<TM_ProjectStatus> TM_ProjectStatus { get; set; }
}
