//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class MT_CCTR_Structure
{
    public string ID { get; set; }
    public string Description { get; set; }
    public string Business_Unit { get; set; }
    public string CC_PC_BU { get; set; }
    public string DT_Costcenter { get; set; }
    public string DT_Costcenter_group { get; set; }
    public string Entity { get; set; }
    public string EVP_Costcenter { get; set; }
    public string OWNER { get; set; }
    public string PC_NODE { get; set; }
    public string PERFORMER { get; set; }
    public string PERFORM_FLAG { get; set; }
    public string PoolCCTR { get; set; }
    public string Profitcenter { get; set; }
    public string REVIEWER { get; set; }
    public string REVIEWER_BG { get; set; }
    public string Scaling { get; set; }
    public string ServiceCostcenter { get; set; }
    public string CommonCostcenter { get; set; }
    public string VP_Costcenter { get; set; }
    public string H1_APPROVAL { get; set; }
    public string H2_BU { get; set; }
    public string H3_ENTITY { get; set; }
    public string BudgetHolder { get; set; }
}

public partial class MT_CostCenter
{
    public string CostCenter { get; set; }
    public string ComCode { get; set; }
    public string BudgetHolder { get; set; }
    public string BudgetHolderName { get; set; }
    public string ShortDesc { get; set; }
    public string FullDesc { get; set; }
    public string Active { get; set; }
    public System.DateTime ValidFrom { get; set; }
    public System.DateTime ValidTo { get; set; }
    public string ProfitCenter { get; set; }
    public string CostCat { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateOn { get; set; }
    public string ControlArea { get; set; }
    public string ObjectNumber { get; set; }
    public string LockActualPK { get; set; }
    public string LockPlanPK { get; set; }
    public string PersResp { get; set; }
    public string StdRelation { get; set; }
    public string GeneralName { get; set; }
}

public partial class MT_GLAccount
{
    public string sGLCode { get; set; }
    public string sCompCode { get; set; }
    public string sGLDesc { get; set; }
    public string cStatus { get; set; }
    public string sGLFullDesc { get; set; }
    public string sUpdateBy { get; set; }
    public Nullable<System.DateTime> sUpdateOn { get; set; }
    public string sGLOPXGroup { get; set; }
}

public partial class MT_InternalOrder
{
    public string IO { get; set; }
    public string ComCode { get; set; }
    public string Description { get; set; }
    public string IOType { get; set; }
    public string IOCategory { get; set; }
    public string RespCCTR { get; set; }
    public string CreatedStatus { get; set; }
    public string ReleasedStatus { get; set; }
    public string CompletedStatus { get; set; }
    public string ClosedStatus { get; set; }
    public string DeleteFlag { get; set; }
    public string ProfitCenter { get; set; }
    public string BudgetHolder { get; set; }
    public string BudgetHolderName { get; set; }
    public string ExternalOrder { get; set; }
    public string UpdateBy { get; set; }
    public Nullable<System.DateTime> UpdateOn { get; set; }
    public string ControlArea { get; set; }
    public string ObjectNumber { get; set; }
    public Nullable<System.DateTime> dCreateOn { get; set; }
    public Nullable<System.DateTime> CloseDate { get; set; }
    public string LockStatus { get; set; }
}

public partial class T_Project
{
    public int nProjectID { get; set; }
    public string sProjectCode { get; set; }
    public Nullable<int> nProjectType { get; set; }
    public string sProjectName { get; set; }
    public int nYear { get; set; }
    public string sCostCenterID { get; set; }
    public string sIOID { get; set; }
    public Nullable<int> nMonthStart { get; set; }
    public Nullable<int> nMonthEnd { get; set; }
    public Nullable<decimal> nBudget { get; set; }
    public Nullable<decimal> nBudgetUsed { get; set; }
    public string sInternalD { get; set; }
    public string sExternalD { get; set; }
    public string sObjectiveD { get; set; }
    public Nullable<int> nDimensionID { get; set; }
    public Nullable<int> nDimensionSubID { get; set; }
    public string sOrgID { get; set; }
    public Nullable<int> nOwnerID { get; set; }
    public string sObjective { get; set; }
    public string sBenefit { get; set; }
    public string sRemark { get; set; }
    public string sApproverID { get; set; }
    public bool IsPassApprove { get; set; }
    public int nStatusID { get; set; }
    public bool IsDel { get; set; }
    public bool IsCreateByAdmin { get; set; }
    public int nCreateBy { get; set; }
    public System.DateTime dCreate { get; set; }
    public int nUpdateBy { get; set; }
    public System.DateTime dUpdate { get; set; }
}

public partial class T_Project_Approve
{
    public int nID { get; set; }
    public int nProjectID { get; set; }
    public Nullable<int> nStatusID { get; set; }
    public string sComment { get; set; }
    public Nullable<int> nActionBy { get; set; }
    public Nullable<System.DateTime> dAction { get; set; }
}

public partial class T_Project_File
{
    public int nProjectID { get; set; }
    public bool IsPic { get; set; }
    public int nItem { get; set; }
    public string sFilename { get; set; }
    public string sSysFileName { get; set; }
    public string sPath { get; set; }
    public int nUpdateBy { get; set; }
    public System.DateTime dUpdate { get; set; }
}

public partial class TB_Budget
{
    public int nID { get; set; }
    public string sFilename { get; set; }
    public string sSysFileName { get; set; }
    public string sPath { get; set; }
    public int nRow { get; set; }
    public int nCreateBy { get; set; }
    public System.DateTime dCreate { get; set; }
}

public partial class TB_Budget_Sub
{
    public int nID { get; set; }
    public int nItem { get; set; }
    public int nProjectID { get; set; }
    public int nPeriod { get; set; }
    public string sIOID { get; set; }
    public System.DateTime dPostingDate { get; set; }
    public string sDescription { get; set; }
    public decimal nValInRepCur { get; set; }
    public string sNameOffsetting { get; set; }
    public string sGLID { get; set; }
    public Nullable<int> nObjective { get; set; }
    public int nArea { get; set; }
    public string sInternal { get; set; }
    public string sExternal { get; set; }
    public int nPA { get; set; }
    public int nUpdateBy { get; set; }
    public System.DateTime dUpdate { get; set; }
}

public partial class TB_Change_Owner
{
    public int nID { get; set; }
    public int nProjectID { get; set; }
    public int nOwnerID { get; set; }
    public int nCreateBy { get; set; }
    public System.DateTime dCreate { get; set; }
}

public partial class TB_CostCenter
{
    public string sCostCenterID { get; set; }
    public int nYear { get; set; }
    public string sCostCenterName { get; set; }
    public string sCostCenterHeadID { get; set; }
    public decimal nBudget { get; set; }
    public decimal nBudgetUsed { get; set; }
    public Nullable<int> nCreateBy { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
}

public partial class TB_DateSync
{
    public int nID { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
}

public partial class TB_GLAccount
{
    public string sGLID { get; set; }
    public string sIOID { get; set; }
    public int nYear { get; set; }
    public string sCostCenterID { get; set; }
    public string sGLName { get; set; }
    public decimal nBudget { get; set; }
    public decimal nBudgetUsed { get; set; }
    public Nullable<int> nCreateBy { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
}

public partial class TB_InternalOrder
{
    public string sIOID { get; set; }
    public int nYear { get; set; }
    public string sIOName { get; set; }
    public string sCostCenterID { get; set; }
    public decimal nBudget { get; set; }
    public decimal nBudgetUsed { get; set; }
    public Nullable<int> nCreateBy { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
}

public partial class TB_Map_Budget
{
    public int nID { get; set; }
    public int nYear { get; set; }
    public int nRow { get; set; }
    public bool IsDel { get; set; }
    public int nCreateBy { get; set; }
    public System.DateTime dCreate { get; set; }
    public int nUpdateBy { get; set; }
    public System.DateTime dUpdate { get; set; }
}

public partial class TB_Map_Budget_Sub
{
    public int nID { get; set; }
    public int nItem { get; set; }
    public string sIOID { get; set; }
    public string sGLID { get; set; }
    public int nProjectType { get; set; }
}

public partial class TB_User
{
    public int nUserID { get; set; }
    public string sUserID { get; set; }
    public string sPassword { get; set; }
    public string sPasswordEncrypt { get; set; }
    public string sFirstname { get; set; }
    public string sLastname { get; set; }
    public string sEmail { get; set; }
    public bool IsGC { get; set; }
    public int nRole { get; set; }
    public bool IsActive { get; set; }
    public bool IsDel { get; set; }
    public int nCreateBy { get; set; }
    public System.DateTime dCreate { get; set; }
    public int nUpdateBy { get; set; }
    public System.DateTime dUpdate { get; set; }
}

public partial class TB_User_Permission
{
    public int nUserID { get; set; }
    public int nMenuID { get; set; }
    public Nullable<int> nPermission { get; set; }
}

public partial class TM_Log
{
    public long nLogID { get; set; }
    public Nullable<System.DateTime> dLog { get; set; }
    public Nullable<int> nUserID { get; set; }
    public Nullable<int> nMenuID { get; set; }
    public string sMenuName { get; set; }
    public string sEvent { get; set; }
}

public partial class TM_LogMail
{
    public int nID { get; set; }
    public string sTo { get; set; }
    public string sCc { get; set; }
    public string sSubject { get; set; }
    public string sMessage { get; set; }
    public Nullable<bool> IsSend { get; set; }
    public string sMessage_Error { get; set; }
    public Nullable<System.DateTime> dSend { get; set; }
}

public partial class TM_MasterData
{
    public int nMainID { get; set; }
    public string sName { get; set; }
    public string sDescription { get; set; }
    public bool IsManage { get; set; }
}

public partial class TM_MasterData_Sub
{
    public int nSubID { get; set; }
    public int nMainID { get; set; }
    public string sName { get; set; }
    public string sDescription { get; set; }
    public Nullable<decimal> nOrder { get; set; }
    public bool IsActive { get; set; }
    public bool IsDel { get; set; }
    public Nullable<int> nCreateBy { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
}

public partial class TM_Menu
{
    public int nMenuID { get; set; }
    public string sMenuName { get; set; }
    public Nullable<int> nMenuHead { get; set; }
    public Nullable<int> nLevel { get; set; }
    public string sMenuLink { get; set; }
    public string sIcon { get; set; }
    public Nullable<int> nMenuOrder { get; set; }
    public bool IsActive { get; set; }
}

public partial class TM_Organization
{
    public string sOrgID { get; set; }
    public string sOrgName { get; set; }
    public string sOrgNameAbbr { get; set; }
    public Nullable<int> nLevel { get; set; }
}

public partial class TM_ProjectStatus
{
    public int nStatusID { get; set; }
    public string sStatusName { get; set; }
}
